-- Migration for existing Supabase tables used by Bếp Sỉ Báo Cáo business sync.
-- Use this when tables already exist but sync says a column is missing, for example raw_payload.

alter table public.mcp_routes add column if not exists route_name text;
alter table public.mcp_routes add column if not exists weekday integer;
alter table public.mcp_routes add column if not exists area text;
alter table public.mcp_routes add column if not exists distributor_id text;
alter table public.mcp_routes add column if not exists active boolean default true;
alter table public.mcp_routes add column if not exists note text;
alter table public.mcp_routes add column if not exists sync_status text;
alter table public.mcp_routes add column if not exists raw_payload jsonb default '{}'::jsonb;
alter table public.mcp_routes add column if not exists created_at timestamptz;
alter table public.mcp_routes add column if not exists updated_at timestamptz;
alter table public.mcp_routes add column if not exists synced_at timestamptz;

alter table public.mcp_route_customers add column if not exists route_id text;
alter table public.mcp_route_customers add column if not exists customer_id text;
alter table public.mcp_route_customers add column if not exists customer_name text;
alter table public.mcp_route_customers add column if not exists phone text;
alter table public.mcp_route_customers add column if not exists area text;
alter table public.mcp_route_customers add column if not exists address text;
alter table public.mcp_route_customers add column if not exists sort_order integer;
alter table public.mcp_route_customers add column if not exists active boolean default true;
alter table public.mcp_route_customers add column if not exists note text;
alter table public.mcp_route_customers add column if not exists geo_lat double precision;
alter table public.mcp_route_customers add column if not exists geo_lng double precision;
alter table public.mcp_route_customers add column if not exists geo_accuracy double precision;
alter table public.mcp_route_customers add column if not exists geo_captured_at timestamptz;
alter table public.mcp_route_customers add column if not exists geo_source text;
alter table public.mcp_route_customers add column if not exists google_maps_url text;
alter table public.mcp_route_customers add column if not exists sync_status text;
alter table public.mcp_route_customers add column if not exists raw_payload jsonb default '{}'::jsonb;
alter table public.mcp_route_customers add column if not exists created_at timestamptz;
alter table public.mcp_route_customers add column if not exists updated_at timestamptz;
alter table public.mcp_route_customers add column if not exists synced_at timestamptz;

alter table public.mcp_route_sessions add column if not exists route_id text;
alter table public.mcp_route_sessions add column if not exists route_name text;
alter table public.mcp_route_sessions add column if not exists session_date date;
alter table public.mcp_route_sessions add column if not exists weekday integer;
alter table public.mcp_route_sessions add column if not exists sales text;
alter table public.mcp_route_sessions add column if not exists area text;
alter table public.mcp_route_sessions add column if not exists status text;
alter table public.mcp_route_sessions add column if not exists planned_customers integer default 0;
alter table public.mcp_route_sessions add column if not exists visited_customers integer default 0;
alter table public.mcp_route_sessions add column if not exists order_count integer default 0;
alter table public.mcp_route_sessions add column if not exists test_count integer default 0;
alter table public.mcp_route_sessions add column if not exists report_count integer default 0;
alter table public.mcp_route_sessions add column if not exists note text;
alter table public.mcp_route_sessions add column if not exists sync_status text;
alter table public.mcp_route_sessions add column if not exists raw_payload jsonb default '{}'::jsonb;
alter table public.mcp_route_sessions add column if not exists created_at timestamptz;
alter table public.mcp_route_sessions add column if not exists updated_at timestamptz;
alter table public.mcp_route_sessions add column if not exists synced_at timestamptz;

alter table public.mcp_visits add column if not exists session_id text;
alter table public.mcp_visits add column if not exists route_id text;
alter table public.mcp_visits add column if not exists route_customer_id text;
alter table public.mcp_visits add column if not exists visit_date date;
alter table public.mcp_visits add column if not exists status text;
alter table public.mcp_visits add column if not exists has_order boolean default false;
alter table public.mcp_visits add column if not exists has_test boolean default false;
alter table public.mcp_visits add column if not exists has_report boolean default false;
alter table public.mcp_visits add column if not exists order_id text;
alter table public.mcp_visits add column if not exists test_id text;
alter table public.mcp_visits add column if not exists report_id text;
alter table public.mcp_visits add column if not exists checkin_at timestamptz;
alter table public.mcp_visits add column if not exists note text;
alter table public.mcp_visits add column if not exists sync_status text;
alter table public.mcp_visits add column if not exists raw_payload jsonb default '{}'::jsonb;
alter table public.mcp_visits add column if not exists created_at timestamptz;
alter table public.mcp_visits add column if not exists updated_at timestamptz;
alter table public.mcp_visits add column if not exists synced_at timestamptz;

alter table public.orders add column if not exists order_code text;
alter table public.orders add column if not exists order_date date;
alter table public.orders add column if not exists sales text;
alter table public.orders add column if not exists customer_id text;
alter table public.orders add column if not exists customer_name text;
alter table public.orders add column if not exists customer_phone text;
alter table public.orders add column if not exists area text;
alter table public.orders add column if not exists delivery_address text;
alter table public.orders add column if not exists source_type text;
alter table public.orders add column if not exists source_id text;
alter table public.orders add column if not exists status text;
alter table public.orders add column if not exists subtotal numeric default 0;
alter table public.orders add column if not exists discount_total numeric default 0;
alter table public.orders add column if not exists grand_total numeric default 0;
alter table public.orders add column if not exists note text;
alter table public.orders add column if not exists sync_status text;
alter table public.orders add column if not exists raw_payload jsonb default '{}'::jsonb;
alter table public.orders add column if not exists created_at timestamptz;
alter table public.orders add column if not exists updated_at timestamptz;
alter table public.orders add column if not exists synced_at timestamptz;

alter table public.order_items add column if not exists order_id text;
alter table public.order_items add column if not exists product_id text;
alter table public.order_items add column if not exists product_name text;
alter table public.order_items add column if not exists sku text;
alter table public.order_items add column if not exists unit text;
alter table public.order_items add column if not exists quantity numeric default 1;
alter table public.order_items add column if not exists unit_price numeric default 0;
alter table public.order_items add column if not exists discount numeric default 0;
alter table public.order_items add column if not exists line_total numeric default 0;
alter table public.order_items add column if not exists note text;
alter table public.order_items add column if not exists raw_payload jsonb default '{}'::jsonb;
alter table public.order_items add column if not exists created_at timestamptz;

alter table public.market_reports add column if not exists report_date date;
alter table public.market_reports add column if not exists sales text;
alter table public.market_reports add column if not exists market_area text;
alter table public.market_reports add column if not exists route_name text;
alter table public.market_reports add column if not exists market_type text;
alter table public.market_reports add column if not exists total_shops integer default 0;
alter table public.market_reports add column if not exists competitor_summary text;
alter table public.market_reports add column if not exists price_summary text;
alter table public.market_reports add column if not exists demand_summary text;
alter table public.market_reports add column if not exists company_product_summary text;
alter table public.market_reports add column if not exists opportunity_summary text;
alter table public.market_reports add column if not exists risk_summary text;
alter table public.market_reports add column if not exists next_action text;
alter table public.market_reports add column if not exists note text;
alter table public.market_reports add column if not exists sync_status text;
alter table public.market_reports add column if not exists raw_payload jsonb default '{}'::jsonb;
alter table public.market_reports add column if not exists created_at timestamptz;
alter table public.market_reports add column if not exists updated_at timestamptz;
alter table public.market_reports add column if not exists synced_at timestamptz;

create index if not exists idx_mcp_route_customers_route_id on public.mcp_route_customers(route_id);
create index if not exists idx_mcp_sessions_route_date on public.mcp_route_sessions(route_id, session_date);
create index if not exists idx_mcp_visits_session_id on public.mcp_visits(session_id);
create index if not exists idx_mcp_visits_customer_id on public.mcp_visits(route_customer_id);
create index if not exists idx_orders_order_date on public.orders(order_date);
create index if not exists idx_order_items_order_id on public.order_items(order_id);
create index if not exists idx_market_reports_report_date on public.market_reports(report_date);

notify pgrst, 'reload schema';
